# Configuración de GitHub Pages
theme: Mediumish
title: AESports | Documentales top del fútbol mexicano 
description: Sitio web la agencia AESports. 
baseurl: "#" # Si tu repositorio está en la raíz del dominio
url: "https://zucar0.github.io/" # URL de tu sitio web

# Configuración de Jekyll
lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge